# Generated by Django 3.2.25 on 2024-08-24 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_videoproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoproxy',
            options={'verbose_name': 'Published Video ', 'verbose_name_plural': 'Published Videos'},
        ),
    ]
