# Generated by Django 3.2.25 on 2024-08-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20240824_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='choices',
            field=models.CharField(choices=[('PU', 'Publish'), ('DR', 'Draft')], default='DR', max_length=2),
        ),
    ]
