# Generated by Django 3.2.25 on 2024-08-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_video_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='choices',
            new_name='state',
        ),
    ]
