# Generated by Django 3.2.25 on 2024-08-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_rename_choices_video_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='publish_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
