# Generated by Django 3.2.25 on 2024-08-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0010_auto_20240827_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('playlists.playlist',),
        ),
    ]
